### ISSUE TITLE
Feature suggestion: Provide DMG file for MacOS users

### ISSUE THREAD

**Issue by tomekw** [AdaCore/gnatstudio#10]
It would be super nice to have simple method of installation on MacOS.

Alternative (preferred) option would be to provide Homebrew / Homebrew Cask recipe (I could contribute to that when provided with DMG file).

Thanks!

**Comment by setton** [comment]
Agreed this would be nice! It's been on our TODO list for a while.

**Comment by tomekw** [comment]
Hi @setton! Any update on this? :)

**Comment by AnthonyLeonardoGracio** [comment]
@tomekw we no longer support GNAT Studio on Mac OS, but you can have a look to our [VS Code Extension for Ada](https://marketplace.visualstudio.com/items?itemName=AdaCore.ada), which is available on Mac OS.

Regards
