### ISSUE TITLE
Vim Plugin: using the b/w motion keys at beginning/end of file causes hang

### ISSUE THREAD

**Issue by spocino** [AdaCore/gnatstudio#121]
If you press the b key at the beginning of the file or the w key at the end of the file, the plugin (presumably) goes into an infinite loop, causing the entire IDE to become unresponsive. This problem persists in both the "normal" and "visual" modes. If somebody can point me to the source code for the vim plugin, I would be happy to fix it and make a PR.

**Comment by 0rzech** [comment]
@spocino If I'm not wrong, what you're looking for is either [vi.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vi.py) or [vim.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vim.py).

**Comment by 0rzech** [comment]
@spocino If I'm not wrong, what you're looking for is either [vi.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vi.py) or [vim.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vim.py), but you might be interested in reading this [comment](https://github.com/AdaCore/gnatstudio/issues/36#issuecomment-449010225) first.

**Comment by 0rzech** [comment]
@spocino If I'm not wrong, what you're looking for is either [vi.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vi.py) or [vim.py](https://github.com/AdaCore/gnatstudio/blob/master/share/library/vim.py), but you might be interested in reading [this comment](https://github.com/AdaCore/gnatstudio/issues/36#issuecomment-449010225) first.
