### ISSUE TITLE
How to write a GNAT Studio / VSCode plugin benefiting the LSP ?

### ISSUE THREAD

**Issue by jgueytat** [AdaCore/gnatstudio#123]
Hi guys,

I wish to create a GNAT Studio / VSCode plugin which would call the Ada language server underlying. My plugin is developped in Python.

- How can I call the LSP through a GNAT Studio plugin ?
- How can I call the LSP with Postman directly (GNAT Studio installed on Windows 10) ?
- How can I call the LSP through a VSCode plugin ? (extra)

Thanks for your help !

**Comment by jgueytat** [comment]
I guess using the LSP API would be to write a "generic plugin" for any language.

I'm only interested in writting an Ada plugin so I could use the libadalang library directly. The libadalang Python API seems to be the way to go.

**Comment by setton** [comment]
Indeed, the general answer (that is, without knowing anything else about your plugin) is to use the Python LAL API :)
