### ISSUE TITLE
GNATCOLL projects constraint error.

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/gnatstudio#128]
I am wondering if there is an issue with new versions of Python (3.10.5) I believe I filed the issue below in the wrong repo?

https://github.com/AdaCore/gnatcoll-core/issues/64

I received the following output when hitting run in a brand new  alire 1.2.0 project

```
Uncaught exception in workflows:
Traceback (most recent call last):
  File "/usr/local/GNAT/CR/share/gnatstudio/support/ui/workflow_buttons.py", line 133, in build_main
    r0 = yield builder.wait_on_execute(main_name)
  File "/usr/local/GNAT/CR/share/gnatstudio/support/ui/workflows/promises.py", line 1108, in wait_on_execute
    self.__target.execute(main_name=main_name,
  File "/usr/local/GNAT/CR/share/gnatstudio/support/core/extensions/__init__.py", line 380, in execute
    self._internal_execute(
GPS.Unexpected_Exception: unexpected internal exception raised CONSTRAINT_ERROR : gnatcoll-projects.adb:5729 index check failed
[/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgnatcoll.so.23.0w]
0x7f226de179c1 gnatcoll__projects__compute_scenario_variables__register_untyped_var.1798.constprop.0 at ???
0x7f226de17d06 gnatcoll__projects__compute_scenario_variables__register_var.1778 at ???
0x7f226de238c7 gnatcoll__projects__for_each_external_variable_declaration at ???
0x7f226de26235 gnatcoll__projects__compute_scenario_variables at ???
0x7f226de271aa gnatcoll__projects__scenario_variables__3.part.0 at ???
0x7f226de27319 gnatcoll__projects__scenario_variables at ???
[/usr/local/GNAT/CR/bin/gnatstudio_exe]
0x3cdd374
0x3ced445
0x3cf1c97
0x43de971
0x444b1c1
0x344b280
0x3cf4662
0x3cf5dce
0x3d06fce
[/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgnatcoll_python3.so.23.0w]
0x7f226f8237bb
0x7f226f8276b2
[/usr/local/GNAT/CR/bin/gnatstudio_exe]
0x5197c89
0x5157bfa
0x515b27b
0x2ba53dc
0x520f0ef
0x5158a9f
0x515b231
0x2ba01b9
0x520f0ef
0x5158a9f
0x2ba32ef
0x52dc2a4
0x5310be8
0x5198478
0x2ba87a5
0x520f0ef
0x5158a9f
0x2ba05bb
0x520f0ef
0x5158a9f
0x2ba05bb
0x520f0ef
0x5158a9f
0x2ba53dc
0x52dc2a4
0x5310be8
0x5198478
0x2ba87a5
0x520f0ef
0x5158a9f
0x2ba05bb
0x520f0ef
0x5158a9f
```

**Comment by kevlar700** [comment]
I need to look into this some more, perhaps the .gnatstudio folder. As I have a machine that is mostly identical without showing this exception. It is also alr 1.1.3 and not 1.2 on the working one.

**Comment by kevlar700** [comment]
Yes it seems to happen with alr 1.2 but not 1.1.3

**Comment by mosteo** [comment]
> Yes it seems to happen with alr 1.2 but not 1.1.3.

As an idea if you have the time you could try bisecting to see where the problem started. My guess is that it will be in some of the new profiles/configuration features that have changed the project files we generate. But I don't know if this will help much given that you already have sample project files that fail.

**Comment by cbvi** [comment]
I got the same issue just trying to open a gpr file that was freshly created with alr init. The issue appears to be `Ada_Compiler_Switches` in the config/\<proj\>_config.gpr file.

Crashes:

       Ada_Compiler_Switches := External_As_List ("ADAFLAGS", " ") & ("-Og");

Works:

       Ada_Compiler_Switches := ("-Og");

Works:

    Ada_Compiler_Switches := External_As_List ("ADAFLAGS", " ");

**Comment by plestedr** [comment]
Same as @cbvi 

Replaced a big list of compiler switches with "  Ada_Compiler_Switches := ("-Og") & ("-gnatwa"); " on one line and I was back in business.

**Comment by t-14** [comment]
This was fixed by https://github.com/AdaCore/gnatcoll-core/commit/0553172078189cdbc381f66a510880290f876c3e
Until alr gets updated this is the right workaround.
