### ISSUE TITLE
[Building gnatstudio] Dependencies completeness in source archive?

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gnatstudio#130]
I aim to build Gnat Studio on macOS starting with Linux source: gnatstudio-sources-x86_64-linux.tar.gz from [gnatstudio-cr-20220512](https://github.com/AdaCore/gnatstudio/releases/tag/gnatstudio-cr-20220512).

The readme says: "An install of Python which includes PyGObject and Pycairo".
Python-3.9.9.tgz is included in the archive whereas PyGObject nor Pycairo aren't included.

Which sources of PyGObject and Pycairo have been used for gnatstudio-cr-20220512?

**Comment by AdrienBoulanger** [comment]
Hi Blady-Com,
If you look at gnatstudio-23.0w-20220512-x86_64-linux-bin/share/gnatstudio/python/lib/python3.9/site-packages then you can check the embedded python dependencies. For this version, pycairo-1-20.1 and PyGobject-3.40.0.
