### ISSUE TITLE
binary release of als seems not working well with gnatstudio binary release in Linux

### ISSUE THREAD

**Issue by qunying** [AdaCore/gnatstudio#131]
If I replace the ada_langague_server that comes with gnatstudio with the new binary release from https://github.com/AdaCore/ada_language_server, then the editing does not function properly (e.g adding new line after a statement does not have proper indent, not tested other features, as this one alone makes the editing experience really bad.) , is it  a bug in ada_language_server or gnatsutdio?

I only tested under Linux, did not try on other platform.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @qunying,

We package a specific version of the `Ada Language Server` with GNAT Studio, which is different from the extension's one in most cases. So replacing it like this is clearly not recommended.

If you want to benefit from the latest improvements made in the `Ada Language Server`, I would suggest you to use it from VS Code directly. Note that we have also release a new version of GNAT Studio last week.

Regards,
