### ISSUE TITLE
Bug in Ada.Integer_Text_Io ? 

### ISSUE THREAD

**Issue by RobG9876** [AdaCore/gnatstudio#144]
Working with/on
OS: Windows 10
GNAT Studio Community 2021 (20210423) hosted on x86_64-w64-mingw32
GNAT Community 2021 (20210519-103) targeting x86_64-w64-mingw32

Problem:
Suppose I have the following string: "01:02:03",
then parsing it with Ada.Integer_Text_IO.Get (<string>, <value>, <last>) results in a DATA_ERROR exception.
Changing the colons to any other non-numeric, '#' excluded, the string parses correctly. Given the definition of numeric literal in the ARM I believe this is a bug.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @RobG9876,

This is not a GNAT Studio related issue, so closing it.

Regards,
