### ISSUE TITLE
Scroll bar colors not consistent 

### ISSUE THREAD

**Issue by AlexandreMarkus** [AdaCore/gnatstudio#151]
![PXL_20230126_144740999.jpg](https://user-images.githubusercontent.com/59664238/214866785-ea60788f-6be6-4849-aacc-62d78ffeabcf.jpg)

I would like all the scroll bars to have the same color. The ones from the text editor are more transparent and difficult to see. Would be nice if it could be the same color than the one from messages box

**Comment by AnthonyLeonardoGracio** [comment]
Hello @AlexandreMarkus ,

The transparency is needed to view the little color marks that might indicate messages on the lines, see the attached screenshot.

Note that you can customize this using CSS, via a `~/.gnatstudio/gps.css` file.

Regards,

<img width="134" alt="Capture d’écran 2023-05-19 à 15 50 15" src="https://github.com/AdaCore/gnatstudio/assets/5286422/56e30f4e-eb87-46d3-8e5e-2c76c66e583b">
