### ISSUE TITLE
Unable to build - python error with newline

### ISSUE THREAD

**Issue by bib1963** [AdaCore/gnatstudio#156]
Trying to build with python 3.6 & 3.10.

Both return the following error:
```
b@eth6:/home/src/build/Ada/gnatstudio> make
make -C gnatstudio default
make[1]: Entering directory '/home/src/build/Ada/gnatstudio/gnatstudio'
cd ../kernel/src; python hooks.py
Traceback (most recent call last):
  File "hooks.py", line 2137, in <module>
    generate_doc()
  File "hooks.py", line 2064, in generate_doc
    newline="\n")
TypeError: 'newline' is an invalid keyword argument for this function
make[1]: *** [Makefile:44: all] Error 1
make[1]: Leaving directory '/home/src/build/Ada/gnatstudio/gnatstudio'
make: *** [Makefile:21: all] Error 2
```

I also have `python2` installed and this is linked from `/usr/bin/python`. That is not going to change since my distro requires it to function properly.

In `gnatstudio/gnatstudio/Makefile`, there is a line:
`PYTHON=python`

This should be picking up whatever is configured, through the `configure` script, or by interrogating the `PYTHON` & `PYTHON_VERSION=`  environmental variables.

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

We use Python 3.9.9 on our side. Could you try with it?

Regards,
