### ISSUE TITLE
With binder shared, unable to automatically set exception breakpoint

### ISSUE THREAD

**Issue by Fratee** [AdaCore/gnatstudio#158]
When launching in debug mode I get the following error:
```
file D:/Frate/GIT/project/program.exe
Reading symbols from D:\Frate\GIT\project\program.exe...done.
(gdb) catch exception
Unable to insert catchpoint. Try to start the program first.
```

this is due to the following option in the project file:
```
package Binder is
    for Switches ("ada") use ("-shared");
end Binder;
```

Is this expected behaviour?

GNAT Studio 23.0 (20221010)

**Comment by setton** [comment]
Hello,

This is not related to GNAT Studio - but rather a debugger question. 

If you are a GNAT Pro customer, don't hesitate to open a ticket on the AdaCore support - we'll be able to follow up on debugger questions there.
