### ISSUE TITLE
Where's the Macintosh release?

### ISSUE THREAD

**Issue by ghost** [AdaCore/gnatstudio#160]
I searched all over for the Macintosh version of GNAT studio and I can't find it.  I remember a few years ago, AdaCore stopped supporting the Macintosh due to technical obstacles, but later I stumbled upon version 23.0w (20220512) which I am running on Monterey.  Is there a reason why the Mac isn't supported?

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

We no longer provide the GNAT compiler on Mac OS, which makes it very difficult to build GNAT Studio on this platform on a daily basis. We still provide the [VS Code extension ](https://github.com/AdaCore/ada_language_server) on Mac OS though.

Regards,
