### ISSUE TITLE
Idea: split comments and literal strings on Return keypress

### ISSUE THREAD

**Issue by zertovitch** [AdaCore/gnatstudio#162]
A very cool feature would be that when the cursor is within a comment and the user presses Return, the comment is split into two comments. Concretely, the editor would add "--  " right after the possible indentation.
Same for string literals.
You can see this feature in action in the LEA editor.
For the code in LEA, see https://github.com/zertovitch/lea/blob/master/lea_gwin-editor.adb and spot `in_ada_comment` and `in_ada_string_literal`.

**Comment by ogorodnik** [comment]
Hello,

Could you have a look on the following blog post:

https://blog.adacore.com/new-features-for-string-literals-and-comments-in-gnat-studio

As far as I understand that is what you need.

**Comment by zertovitch** [comment]
Yes - lovely!
