### ISSUE TITLE
gnatdoc: Unexpected reappearance of previous parameter for custom tags present in the same line

### ISSUE THREAD

**Issue by mgrojo** [AdaCore/gnatstudio#166]
Given this input:

```ada
--/ The @a pixel array is assumed to contain 32-bits RGBA pixels,
--/ and have the given @a width and @a height. If not, this is
--/ an undefined behaviour.
--/ If @a pixels is null, an empty image is created.
```

And this tag definition:

```python

class ATagHandler(GPS.InlineTagHandler):
    def __init__(self):
        super(ATagHandler, self).__init__('a')

    def has_parameter(self):
        return True

    def to_markup(self, writer, parameter):
        writer.html(' <em>%s</em> ' % parameter)
```

The expected output is:

> The _pixel_ array is assumed to contain 32-bits RGBA pixels, and have the given _width_ and _height_. If not, this is an undefined behaviour. If _pixels_ is null, an empty image is created. 

But the actual output is:
> The _pixel_ array is assumed to contain 32-bits RGBA pixels, and have the given _width_ and _width_ _height_. If not, this is an undefined behaviour. If _pixels_ is null, an empty image is created. 

Note the spurious inclusion of _width_ where only _height_ is placed in the source. It happens for all the custom tags that appear more than once in the same source line. This is why _pixels_  and _pixel_ are not repeated.

The problem can be observed here:

https://mgrojo.github.io/ASFML/doc/docs/sf__graphics__image___spec.html#L77C13

Reproduced with GNAT Studio 2021 and https://github.com/AdaCore/gnatstudio/releases/tag/gnatstudio-cr-20230501

**Comment by AnthonyLeonardoGracio** [comment]
Hello, 

We have recently revamped GNATdoc: it's now based on Libadalang. We will have look, maybe this issue is not present anymore with the latest version. Keeping you posted.

Regards,

**Comment by godunko** [comment]
Hello,

We strongly recommends to use new generation of the GNATdoc tool. It will be available in the next GNAT Studio Community Edition, as well as Alire crate.

New GNATdoc will supports many Markdown formatting features, you don't need to use custom plugins for formatting of the italic/bold/monospace inline text, but can use corresponding Markdown features (emphasis/strong emphasis/code span).
