### ISSUE TITLE
Autocomplete Delimiters

### ISSUE THREAD

**Issue by moraesid** [AdaCore/gnatstudio#175]
I'm testing Gnat Studio for c/c++ development, but I couldn't identify a feature.

How to enable "code autocomplete" for delimiters such as [], {}, () ?

**Comment by AnthonyLeonardoGracio** [comment]
Hello @moraesid,

GNAT Studio is using `clangd` as a LSP language server for C/C++, so if the feature is available in `clangd` via a command-line option, you should be able to append it in the `LSP` preferences page, via the `clangd/Command line arguments` option.

Note that GNAT Studio itself does not provide automatic completion for delimiters: this is to avoid conflicts between GNAT Studio and the underlying language servers (either for Ada or C/C++) that might append closing delimiters too in some cases.

Regards,
