### ISSUE TITLE
Finalizable and pragma Extensions_Allowed  (All_Extensions)

### ISSUE THREAD

**Issue by evanescente-ondine** [AdaCore/gnatstudio#179]
Hi, I'm an Ada student which likes to use the latest syntax in my exos, at least whenever it seems sound.
Here it is about the new generalized finalization, bebcause I don't like making tagged types when I want a feature wholly unrelated to object programming.

```
procedure Initialize (N: in out Pack);
type Pack (Number: CardNumber := 52) is record
	List: CardArray(1..Number);
end record
	with Finalizable => (Initialize => Initialize);
```		
> card_package.ads:33:22: warning: "Finalizable" is not a valid aspect identifier [enabled by default]

I know I could do this differently... and used to do, with a default value for List. But since it's abouit initialization, I thought I could use, well, real initizalization instead.

```
pragma Ada_2022;
pragma Extensions_Allowed(All);
```
I have "All" because otherwise I get
>  card_package.ads:2:27: error: argument for pragma "Extensions_Allowed" must be "On" or "Off" or "All"

Not normal, so I can't get the experimental features ?
My version is GNAT 13.3.0

Thanks.

**Comment by evanescente-ondine** [comment]
Sorry, I wasn't clear and wasted your time. Let's have another go: This is on your [website](https://gcc.gnu.org/onlinedocs/gnat_rm/How-to-activate-the-extended-GNAT-Ada-superset.html):
> Attention: You can activate the extended set of extensions by using either the -gnatX0 command line flag, or the pragma Extensions_Allowed with All_Extensions as an argument.

This is a sample of code that fails:
```
pragma Ada_2012;
pragma Extensions_Allowed (All_Extensions);
procedure Essai is
	type Pack is null record with Finalizable => (Initialize           => Init);
	procedure Init (N: in out Pack) is null;
begin
	null;
end Essai;
```
with this message:
> essai.adb:2:28: error: argument for pragma "Extensions_Allowed" must be "On" or "Off" or "All"
essai.adb:4:39: warning: "Finalizable" is not a valid aspect identifier [enabled by default]
gnatmake: "essai.adb" compilation error

**Comment by raph-amiard** [comment]
Hi evanescente,

Our docs are live generated from the nightly version of our compiler and tools. The options you are refering to are just not yet available in the community compilers. For community compilers we follow the GCC release schedule, so those should be available in the next release!

Kind regards
