### ISSUE TITLE
Some Gnat GPS function might work incorrect on WIn32 if Cygwin in PATH

### ISSUE THREAD

**Issue by timurgen** [AdaCore/gnatstudio#41]
It doesn't actually a GPS issue I guess, but still good to know. 
If you use GNAT GPS on Windows machine and have Cygwin tool chain  (with installed gcc-ada library) in PATH, some GPS functions such as Smart Completion will not work.

**Comment by AnthonyLeonardoGracio** [comment]
Hi,

So if the Cygwin toolchain is not in your PATH the Smart Completion works? Because the PATH variable and the Smart Completion should be completely unrelated, that would be really strange.

**Comment by timurgen** [comment]
@AnthonyLeonardoGracio  Hi, correct, when I remove Cygwin from PATH everything works fine, when I add it, things go wrong. It affects not only Smart Completion but for example Search functions. Probably conflicting binaries can confuse GPS in some manner?

**Comment by AnthonyLeonardoGracio** [comment]
@timurgen 

This should be fixed now that we use the `Ada Language Server` for completion and other language intelligence features (tooltips, navigation etc.)

Regards
