### ISSUE TITLE
GNATtest integration does not allow test harnesses outside of the object directory

### ISSUE THREAD

**Issue by rtyler** [AdaCore/gnatstudio#43]
I have been attempting to use the GNATtest integration within GPS to maintain a test suite but it seems that there is simply no way to configure the project settings to accommodate a test directory which is **not** inside the object directory.

I would like to put things _outside_ of the object directory because putting test sources which **I** am editing inside the object directory is counter intuitive and forces me to check parts of the object directory into source control :frowning: 

`gnattest` has no problem generating a test harness _anywhere_ in the source tree, but the [GPS integration](https://docs.adacore.com/gps-docs/users_guide/_build/html/tools.html#working-with-unit-tests) will simply ignore an existing test harness outside of the object directory and generate a new one _in_ the object directory.

**Environment**

```
GPS 2018 (20180528) hosted on x86_64-pc-linux-gnu
GNAT Community 2018 (20180524-73
```

**Comment by fedor-rybin** [comment]
Thank you for your report, we will investigate.
In the meantime you can specify harness dir by corresponding attribute in your project file, GPS picks that one up.

**Comment by reznikmm** [comment]
> In the meantime you can specify harness dir by corresponding attribute in your project file, 

Just put this in your project file:
```
   package GNATtest is
      for Harness_Dir use "my_hd";
   end GNATtest;
```
