### ISSUE TITLE
Warning options doesn't remain in same order after GUI modification.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gnatstudio#65]
Hello,
My compiler options are:
      for Default_Switches ("ada") use ("-gnatw.eH.YD", "-g");

When I modified the options with the GUI, cancel -g for instance, the order of the compiler warning options are modified:
      for Default_Switches ("ada") use ("-gnatw.Y.eDH");

Sadly the meaning is not the same because .Y is before .e.

Configuration: GPS Community 2018, macos 10.13.6 (17G5019).

HTH, Pascal.

**Comment by ogorodnik** [comment]
Indeed it is a bug. Will be fixed.

**Comment by AnthonyLeonardoGracio** [comment]
@Blady-Com 

Hello,

This is now fixed in the latest version of GNAT Studio. Thanks for the report!

Regards,
