### ISSUE TITLE
Debug target doesn't open dialogue

### ISSUE THREAD

**Issue by benconvey** [AdaCore/gnatstudio#71]
As per the title, setting my debug target to open with a dialogue doesn't open said dialogue. Please see the video with the attached zipped folder.

As a side note, where are the XML files to edit the python targets? The manual references them  [here](https://docs.adacore.com/gps-docs/users_guide/_build/html/extending.html#customizing-build-targets-and-models) but I cant find them anywhere within my install, nor a button to open them for that matter.

[debug_target_dialogue.zip](https://github.com/AdaCore/gps/files/3160773/debug_target_dialogue.zip)

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

We can reproduce this issue, which looks related to an exception that occurs.

However, note that the 'Build & Debug' target calls some predefined Python code, so you won't be able to customize GDB's command line from this dialog for instance.

Regards,
