### ISSUE TITLE
Adjusting project properties after creating scenario variable consumes existing global settings

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gnatstudio#74]
Begin with

~~~~
type Platform_Type is ("UNIX", "Windows");
Platform : Platform_Type := external("Platform");

case Platform is
    when "UNIX" => for Source_Dirs use ("Common", "UNIX");
    when "Windows" => for Source_Dirs use ("Common", "Windows");
end case;

for Object_Dir use "objects";
for Library_Dir use "libraries"
--… and so on

package Compiler is
    for Default_Switches("Ada") use ("-O2", "-gnatA", "-gnatW8", "-fPIC", "-shared");
    --… and so on
end Compiler;
~~~~

So clearly there are a bunch of global settings, and it's just `Source_Dirs` that changes depending on the target platform.

I go through the GUI to add "-gnato" and "-gnatE" to the compiler switches.

I now have this

~~~~
type Platform_Type is ("UNIX", "Windows");
Platform : Platform_Type := external("Platform");

case Platform is
    when "UNIX" =>
        for Source_Dirs use ("Common", "UNIX");
        for Object_Dir use "objects";
        for Library_Dir use "libraries"
        --… and so on
    when "Windows" =>
        for Source_Dirs use ("Common", "Windows");
        for Object_Dir use "objects";
        for Library_Dir use "libraries"
        --… and so on

package Compiler is
    for Default_Switches("Ada") use ("-O2", "-gnatA", "-gnatW8", "-fPIC", "-shared", "-gnato", "-gnatE");
    --… and so on
end Compiler;
~~~~

So I mean, it didn't add those new settings inside of a case like with #63, but this clearly isn't acceptable behavior either. Now, if I update the library version number, and important thing to keep accurate, it only updates for one platform. This is made considerably worse in that GPS decided to also place `Library_Interface` within the case statement as well, so I would now need to maintain two copies of the SAL interface!

**Comment by Entomy** [comment]
Bah, I forgot again, this is with build 20190106

**Comment by ogorodnik** [comment]
Hello Entomy,
We can reproduce this. We will let you know when it is fixed.
Thank you for the report.

**Comment by AnthonyLeonardoGracio** [comment]
Too complicated to solve with the current engine based on GNATCOLL, will be solved once we have a proper language server for GPR.
