### ISSUE TITLE
Feature suggestion: Add F# support to GPS

### ISSUE THREAD

**Issue by financial-engineer** [AdaCore/gnatstudio#8]
Dear GPS developers!

GPS has already supported C#. Please add the same support to F# in the 2017 release of GPS. 
F# is a functional-imperative, object-oriented language with growing popularity. The F# compiler and tools are shipped along with the C# compiler and tools as part of Microsoft Visual Studio 2015.

**Comment by setton** [comment]
Hello! It's not a high-priority in GPS to support F# - I suppose the majority of F# users will use Visual Studio for this, wouldn't they?

This said, there are a lot of things that can be done through plugins, there is basic support for adding [new languages](http://docs.adacore.com/gps-docs/users_guide/_build/html/extending.html#adding-support-for-new-languages) and there is also a quite advanced mechanism for [defining syntax highlighters](http://docs.adacore.com/gps-docs/users_guide/_build/html/extending.html#defining-custom-highlighters), which we use for highlighting C and Python - perhaps this should be enough to add basic support for F#? If you want to have a go and submit a F# plugin, we'll be happy to help.
