### ISSUE TITLE
hooks.py should be called with `python2`

### ISSUE THREAD

**Issue by Rodeo-McCabe** [AdaCore/gnatstudio#98]
Trying to build on Linux, and getting the following error:

```
$ make
make -C gnatstudio default
make[1]: Entering directory '/home/darby/Upstreams/gps/gnatstudio'
cd ../kernel/src; python hooks.py
Traceback (most recent call last):
  File "hooks.py", line 2095, in <module>
    generate()
  File "hooks.py", line 1099, in generate
    f.write('''--  Automatically generated from hooks.py
TypeError: a bytes-like object is required, not 'str'
make[1]: *** [Makefile:42: all] Error 1
make[1]: Leaving directory '/home/darby/Upstreams/gps/gnatstudio'
make: *** [Makefile:21: all] Error 2
```

Adjusting the Makefiles so they call `python2` fixes this problem. Since Python 2 is officially past End Of Life, this should be adjusted.

**Comment by godunko** [comment]
Thank you for report, transition to Python 3 is on our roadmap.

**Comment by Rodeo-McCabe** [comment]
This issue should not be closed as I am not asking to transition to Python 3. I am asking that the existing Python 2 code be called correctly: with the command `python2`. 

Python 2 is officially past end of life (and has been officially deprecated for **ten years**), and the command `python` now refers to Python 3 on many Linux distributions. This goes against the [PEP 394](https://legacy.python.org/dev/peps/pep-0394/#recommendation) recommendation, however the PEP 394 also states the following:

> In order to tolerate differences across platforms, all new code that needs to invoke the Python interpreter should not specify python, but rather should specify either `python2` or `python3`

Note that this recommendation was last updated **five years** ago. This change is long overdue.

I would be happy to make a PR with the necessary (and trivial) changes.

**Comment by AnthonyLeonardoGracio** [comment]
Fixed now that GS is full Python 3. Closing the issue.
